### ISSUE TITLE
DigiCert High Assurance EV Root CA Generation

### ISSUE THREAD

**Issue by Maxvi33** [programmer131/ESP8266_ESP32_SelfUpdate#3]
Hello,
this certificate is specific to you ? It's possible to explain how generate own proper certificate for ESP ?

**Comment by programmer131** [comment]
no it isn't specific to me, i'm not using my own server, it is for github. if you have your own domain where you want to host binary file, then you can use your own self signed certificates.

**Comment by emailsidbhatia** [comment]
Hi @programmer131! How did you generate the certificate for github and what is the use of the setClock() function?
Thanks

**Comment by programmer131** [comment]
We can download certificate from Firefox, I didn't generate any certificate myself.
setClock() function takes time from NTP server and configure it into esp8266, it is used for x.509 validation.
