### ISSUE TITLE
Getting Connection failed .

### ISSUE THREAD

**Issue by fridayowl** [programmer131/ESP8266_ESP32_SelfUpdate#5]
Tried copying the same code and changed only the wifi credentials. getting only "connection failed" this message on serial monitor

**Comment by programmer131** [comment]
for esp32?

**Comment by programmer131** [comment]
closing since no follow up

**Comment by programmer131** [comment]
closing since no follow up

**Comment by KARTIK-eng** [comment]
I'm facing the same problem "connection refused"
Firmware update Starting..
16:48:15.042 -> HTTP_UPDATE_FAILD Error (-1): HTTP error: connection refused.
Please help!

**Comment by programmer131** [comment]
for esp8266 ? or esp32?
